[package]
name = "mlld"
version = "0.0.0"
edition = "2024"

[dependencies]
mll-core = { path = "../mll-core", features = ["tokio"] }

clap = { version = "4", features = ["cargo", "env"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
toml = "1"

tokio = { version = "1", features = ["full"] }
futures = "0.3"
pin-project-lite = "0.2"
parking_lot = "0.12"
interprocess = { version = "2", features = ["tokio"] }
axum = "0.8"
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["tokio", "client-legacy"] }

nix = { version = "0.31", features = ["signal"] }
